---
title: "Proposal"
description: |
  A short description of the post.
author:
  - name: Choong Shi Lian Selene, Jiang Weiling Angeline, Wong Wei Sheng Dylan
    url: {}
date: 02-25-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


### Background

### Motivation


### Project Objectives
The project aims to deliver an R-Shiny app that provides interactive user interface design to:
* Understand the correlation of factors affecting greenhouse gases emissions
* Identify important factors which contributes to greenhuose gases emissions using Panel data regression
* Further analyse the difference in greenhuose gases emissions by country and time period

### Proposed Scope and Methodology

### Storyboard & Visualization Features

#### Exploratory Data Analysis

#### Validation Tests

#### Calibration of Model

### Proposed R Packages
#### Data Preparation
* tidyverse: https://www.tidyverse.org

#### Panel data regression
* ExPanDaR: https://cran.r-project.org/web/packages/ExPanDaR
* plm: https://cran.r-project.org/web/packages/plm

#### Building Shiny App
* shiny: https://shiny.rstudio.com
* shinythemes: https://cran.r-project.org/web/packages/shinythemes
* shinyWidgets: https://cran.r-project.org/web/packages/shinyWidgets
* RColorBrewer: https://cran.r-project.org/web/packages/RColorBrewer

### Project Timeline

### Team Members
* Choong Shi Lian Selene
* Jiang Weiling Angeline
* Wong Wei Sheng Dylan

### References

